---

- name: Install texlive
  yum:
    name: texlive
    state: latest

- name: Install transfig
  yum:
    name: transfig
    state: latest

- name: Install texlive-latex
  yum:
    name: texlive-latex
    state: latest

- name: Install texlive-xetex
  yum:
    name: texlive-xetex
    state: latest

- name: Install texlive-collection
  yum:
    name: texlive-collection-latex
    state: latest

- name: Install texlive-collection-latexrecommended
  yum:
    name: texlive-collection-latexrecommended
    state: latest

- name: Install texlive-xetex-def
  yum:
    name: texlive-xetex-def
    state: latest

- name: Install texlive-collection-xetex
  yum:
    name: texlive-collection-xetex
    state: latest

- name: Install inkscape
  yum:
    name: inkscape
    state: latest

- name: Install perl-Digest
  yum:
    name: perl-Digest
    state: latest
