---

- name: Install dkms 
  yum:
    name: dkms
    state: latest

- name: Install make 
  yum:
    name: make
    state: latest

- name: Install kernel-devel
  yum:
    name: kernel-devel
    state: latest

- name: Install bzip2
  yum:
    name: bzip2
    state: latest

- name: Install binutils
  yum:
    name: binutils
    state: latest

- name: Install patch
  yum:
    name: patch
    state: latest

- name: Install libgomp
  yum:
    name: libgomp
    state: latest

- name: Install glibc-headers
  yum:
    name: glibc-headers
    state: latest

- name: Install glibc-devel
  yum:
    name: glibc-devel
    state: latest

- name: Install kernel-headers
  yum:
    name: kernel-headers
    state: latest

- file: 
    path: /media/cdrom
    state: directory
    mode: 0755
   
- name: Mount up guest additions
  mount:
    path: /media/cdrom
    src:  /dev/cdrom
    fstype: ext4
    state: present 

- name: Run shell
  shell: /media/cdrom/VBoxLinuxAdditions.run
