---

- file:
    path: /home/vagrant/VOTCA/
    state: directory
    mode: 0755

- copy:
    src: fftw-libs-3.3.3-8.el7.x86_64.rpm
    dest: /home/vagrant/fftw-libs-3.3.3-8.el7.x86_64.rpm
    mode: 0644

- copy:
    src: fftw-devel-3.3.3-8.el7.x86_64.rpm
    dest: /home/vagrant/fftw-devel-3.3.3-8.el7.x86_64.rpm
    mode: 0644

- name: install fftw3
  yum:
    name: /home/vagrant/fftw-libs-3.3.3-8.el7.x86_64.rpm
    state: present

- name: install fftw3-devel
  yum:
    name: /home/vagrant/fftw-devel-3.3.3-8.el7.x86_64.rpm
    state: present

- name: Install expat
  yum:
    name: expat
    state: latest

- name: Install expat development
  yum:
    name: expat-devel
    state: latest

- name: Install gsl
  yum:
    name: gsl
    state: latest

- name: Install gsl development
  yum:
    name: gsl-devel
    state: latest

- name: Install sqlite3
  yum:
    name: sqlite
    state: latest

- name: Install sqlite-devel
  yum:
    name: sqlite-devel
    state: latest

- name: install git
  yum:
    name: git
    state: present

- name: install compiler
  yum:
    name: gcc-c++
    state: latest

- git:
    repo: https://github.com/votca/votca.git
    dest: /home/vagrant/VOTCA/

- file:
    path: /home/vagrant/VOTCA/build
    state: directory
    mode: 0755

# - name: yum update
#   command: yum update

- name: install cmake
  yum:
    name: cmake3
    state: latest

#- name: install fftw
#  yum:
#    name: fftw3
#    state: latest

- name: install Doxygen
  yum:
    name: doxygen
    state: latest

- name: install TXT2TAGS
  yum:
    name: txt2tags
    state: latest

- name: install boost
  yum:
    name: boost
    state: latest

- name: install boost-devel
  yum:
    name: boost-devel
    state: latest

# - name: install GROMACS
#   yum:
#     name: gromacs
#     state: latest

# - name: upgrade all packages
#   yum:
#     name: '*'
#     state: latest

# - name: remove build folder
#   command: rm -rf /home/vagrant/VOTCA/build

- name: build command 1
  command: cmake3 -DBUILD_CSGAPPS=ON -DBUILD_CTP=ON -DBUILD_XTP=ON ../
  args:
    chdir: /home/vagrant/VOTCA/build

- name: build command 2
  command: make -j5
  args:
    chdir: /home/vagrant/VOTCA/build
