---

- file:
    path: /home/vagrant/VOTCA/
    state: directory
    mode: 0755

- name: Install expat
  yum:
    name: expat
    state: latest

- name: Install expat development
  yum:
    name: expat-devel
    state: latest

- name: Install gsl
  yum:
    name: gsl
    state: latest

- name: Install gsl development
  yum:
    name: gsl-devel
    state: latest

- name: Install sqlite3
  yum:
    name: sqlite
    state: latest

- name: Install sqlite-devel
  yum:
    name: sqlite-devel
    state: latest

- file:
    path: /home/vagrant/VOTCA/build
    state: directory
    mode: 0755

# - name: yum update
#   command: yum update
#- name: install fftw
#  yum:
#    name: fftw3
#    state: latest

- name: install Doxygen
  yum:
    name: doxygen
    state: latest

- name: install TXT2TAGS
  yum:
    name: txt2tags
    state: latest
# - name: install GROMACS
#   yum:
#     name: gromacs
#     state: latest

# - name: upgrade all packages
#   yum:
#     name: '*'
#     state: latest

# - name: remove build folder
#   command: rm -rf /home/vagrant/VOTCA/build

- name: build command 1
  command: cmake3 -DBUILD_CSGAPPS=ON -DBUILD_CTP=ON -DBUILD_XTP=ON ../
  args:
    chdir: /home/vagrant/VOTCA/build

- name: build command 2
  command: make -j5
  args:
    chdir: /home/vagrant/VOTCA/build
